### PR TITLE
Fixed usage instructions in readme

### PR DESCRIPTION
**Pull request by vygis**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
This seems much simpler.

**Comment by mridgway** [comment]
Looks like static assets are not serving correctly for the todo example at least.

**Comment by mridgway** [comment]
Closing for now since it breaks CSS assets.

**Pull request closed without merging**
