### PR TITLE
Print nav links only if they have a label.

### PR DESCRIPTION
**Pull request by robertcasanova**
Otherwise page link in router is displayed with empty label.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by robertcasanova** [comment]
Done, thx!

**Comment by mridgway** [comment]
Is this issue exhibited in flux-examples somewhere? It seems like we should just make that a required `propType` since it seems more like a user error.

**Comment by robertcasanova** [comment]
@mridgway  When i run the fluxible router example, a link is created for every element in config/routes but 'dynamicpage' route has no label associated and also require a param ID, so this link is empty.

**Comment by mridgway** [comment]
Ah, I see. Makes sense. Thanks!

**Pull request merged**
