### PR TITLE
Support non-GET requests in Chat and Fluxible Router examples

### PR DESCRIPTION
**Pull request by tlovett1**
I spent way too much time figuring out how to do this. I realize non-GET requests aren't necessary for these examples, but having code to indicate how to do this is immensely useful.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by cesarandreu** [comment]
Doesn't this open you up to CSRF attacks?

**Comment by tlovett1** [comment]
I don't see how. No routes even support POST so it shouldn't do anything.

**Comment by mridgway** [comment]
I don't think we're going to add this support to the examples until we have a good example of its usage including CSRF protection as @cesarandreu mentioned.

**Pull request closed without merging**
