### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by apaatsio**
These became unused in 322c19472198bc00041c00f0751dd8adba433a26

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by apaatsio** [comment]
No love?

**Comment by redonkulus** [comment]
Sorry about that. Thanks!

**Pull request merged**
