### PR TITLE
Upgrade React to include 0.13.x

### PR DESCRIPTION
**Pull request by mridgway**
`react-router` does not support React@0.13 yet (see https://github.com/rackt/react-router/issues/638) so we are blocked from merging this until they do.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
:shipit:

**Comment by mridgway** [comment]
Updated to new version of packages. Not sure what to do with react-router.

**Comment by mridgway** [comment]
Moved the react-router dependency into the react-router folder's package.json since it's not clear when they will support React 0.13. This allows the rest of the examples install and work correctly. This should be ready to go for now.

**Comment by redonkulus** [comment]
LGTM

**Comment by jedireza** [comment]
Looking good.

**Pull request merged**
