### PR TITLE
Remove `dispatcher` parameter from store `initialize` methods

### PR DESCRIPTION
**Pull request by daannijkamp**
Is there a reason for that in the TodoStore (todo example) , the "dispatcher" is not passed into the initialize function? 
So far i can see applies that only for the TodoStore. The rest of the the stores in this repository are passing the "dispatcher" into the initialize function.

The documentation does also not makes it any clearer.
https://github.com/yahoo/dispatchr#createstore

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by cesarandreu** [comment]
I don't think dispatchr is even passing in the dispatcher instance.. See [here](https://github.com/yahoo/dispatchr/blob/master/utils/BaseStore.js#L21).  Instead, it just sets this.dispatcher, so you can access it in any of your store functions. 

Maybe it used to pass dispatcher to initialize at some point, but it no longer does so? If that's the case then we should probably remove it from the examples?

**Comment by mridgway** [comment]
Yup, I think you found a discrepancy between our example stores and how the initialize function actually works. `initialize` does not receive a dispatcher instance, instead dispatcher is accessible via `this.dispatcher`.

The examples do need to be updated.

**Comment by mridgway** [comment]
If you update your PR to remove all of the `dispatcher` parameters from `initialize` methods, we'll merge it in.

**Comment by daannijkamp** [comment]
Pfff I screwed up. Should i close this pull request and make a new one?

**Comment by mridgway** [comment]
Haha, yeah that's fine.

**Pull request closed without merging**
