### PR TITLE
Fixed path reference in docs

### PR DESCRIPTION
**Pull request by coryhouse**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
Each `cd` statement should probably be its own code block.

**Comment by mridgway** [comment]
I think this README is specifically for the react-router example so I don't think we need this change.

**Pull request closed without merging**
