### PR TITLE
Fixes missing context in NavLink

### PR DESCRIPTION
**Pull request by zol**
Without this the example is broken

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by mridgway** [comment]
Hi @zol, `context` should not have to be passed in her because it is provided by the `FluxibleComponent`'s `getChildContext` method. Child context propagates itself down the component tree.

**Comment by zol** [comment]
Got it, thanks @mridgway, I'm still quite new to react.  This change fixed an exception from `NavLink` where it was accessing an undefined `context`. Unfortunately I can't reproduce the issue again.

**Pull request closed without merging**
