### PR TITLE
Favor child context over React.withContext

### PR DESCRIPTION
**Pull request by joemcbride**
React.withContext is deprecated in v0.13.  This updates the samples to alternatively use a child context.

Related Changes
https://github.com/yahoo/fluxible/pull/52
https://github.com/yahoo/flux-router-component/pull/79

https://github.com/facebook/react/blob/master/src/core/ReactContext.js#L54

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
We'll definitely need to do this. What are your thoughts on making the `getChildContext` declaration part of the `FluxibleMixin`?

**Comment by jedireza** [comment]
:+1: for adding it to `FluxibleMixin`

**Comment by joemcbride** [comment]
:+1:  That makes a lot of sense to me.

**Comment by mridgway** [comment]
Cool, do you want to do a PR to Fluxible and then this PR can updated to use that mixin instead?

**Comment by joemcbride** [comment]
Yes, I will do that tonight.

**Comment by joemcbride** [comment]
@mridgway  I think this is actually ready!

**Comment by mridgway** [comment]
Nice! I'll check it out.

**Comment by mridgway** [comment]
Works great. Many thanks @joemcbride!

**Comment by trungpham** [comment]
to get the existing context, we have to change our code from this.context.myContext to this.props.context.myContext.

**Comment by mridgway** [comment]
@trungpham If you're using the `provideContext` HoC, you will not need to use `this.props.context`. `provideContext` will ensure that `this.context` is populated as long as the components set `contextTypes` correctly.

**Pull request merged**
