### PR TITLE
Updated all references of fluxible-app to fluxible

### PR DESCRIPTION
**Pull request by timReynolds**
Updated all references of fluxible-app to fluxible inline with change made in the latest version 1.5

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by jedireza** [comment]
Thanks @timReynolds!

@mridgway @redonkulus did we want to change the variable names too?

```diff
-var FluxibleApp = require('fluxible-app');
+var Fluxible = require('fluxible');
```

**Comment by timReynolds** [comment]
@jedireza Noticed after I did this that @mridgway beat me to it. Feel free to close.

**Pull request closed without merging**
