### PR TITLE
Delete fluxible-plugin-rr

### PR DESCRIPTION
**Pull request by Maximilianos**
Remove exploratory fluxible-plugin-rr from react-router fluxible example

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Thanks!

**Comment by Maximilianos** [comment]
It is my first ever commit to an external os project, and it is EPIC ;) glad to help!

**Comment by jedireza** [comment]
Woot, welcome to the party! :confetti_ball: :tada:

**Pull request merged**
